-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS article CASCADE;
DROP TABLE IF EXISTS game_users CASCADE;
DROP TABLE IF EXISTS player_character CASCADE;
DROP TABLE IF EXISTS game_session CASCADE;
DROP TABLE IF EXISTS game CASCADE;
DROP TABLE IF EXISTS site_user CASCADE;
DROP TABLE IF EXISTS creation_date CASCADE;
